version: '3'

# 各serviceから参照できる名前付きvolumeを定義
volumes:
  db-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: tail -f /dev/null
  db:
    image: postgres:13.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
