FROM elixir:1.12.2
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends inotify-tools && \
  mix local.hex --force && \
  mix archive.install hex phx_new 1.4.3 --force && \
  mix local.rebar --force
